# Generated by Django 3.2.9 on 2021-12-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='years',
            field=models.ManyToManyField(blank=True, to='users.Year'),
        ),
    ]
