# Generated by Django 3.2.9 on 2021-12-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='years',
            new_name='year',
        ),
    ]
