# Generated by Django 3.2.9 on 2021-12-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_years_profile_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year',
            new_name='years',
        ),
    ]
