# Generated by Django 3.2.9 on 2022-01-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('responsible', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
