# Generated by Django 3.2.9 on 2022-01-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220111_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
