# Generated by Django 4.0.1 on 2022-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_agremiado_number_profile_degree_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ManyToManyField(blank=True, to='users.Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modality',
            field=models.ManyToManyField(blank=True, to='users.Modality'),
        ),
    ]
