# Generated by Django 4.0.1 on 2022-02-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_modality_remove_profile_location_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='compromiso',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='compromiso_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
