# Generated by Django 3.2.12 on 2022-02-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_compromiso_profile_compromiso_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='location',
            name='position_responsible',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
