# Generated by Django 4.0.2 on 2022-02-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_profile_skill_skill_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agremiado_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
