# Generated by Django 4.0.3 on 2022-03-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_location_name_alter_profile_agremiado_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettershistory',
            name='register',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
