# Generated by Django 4.0.3 on 2022-03-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_lettershistory_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
