# Generated by Django 4.0.3 on 2022-03-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_droregister'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='droregister',
            unique_together=set(),
        ),
    ]
