# Generated by Django 4.0.3 on 2022-03-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_droregister_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='droregister',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
