# Generated by Django 4.0.3 on 2022-03-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='users.course', verbose_name='Cursos tomados'),
        ),
    ]
