# Generated by Django 4.0.3 on 2022-04-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_profile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imageWIXURL',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Imangen desde WIX'),
        ),
    ]
